version: '3.3'
services:
    redis-stack:
        container_name: redis-stack
        image: 'redis/redis-stack:6.2.6-v2'
        restart: always
        ports:
            - '6379:6379'
            - '8001:8001'
        volumes:
            - './redis-data/:/data'
            - './redis-stack.conf:/etc/redis-stack.conf'
    mongo:
        container_name: mongo
        image: mongo:6.0.4
        restart: always
        ports:
            - 27017:27017
        volumes:
            - './mongo-data/:/data/db'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    mongo-express:
        container_name: mongo-express
        image: mongo-express:0.54.0
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
            ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    neo4j:
        container_name: neo4j
        image: neo4j:5.5.0
        restart: always
        ports: 
            - 7474:7474
            - 7687:7687
        volumes:
            - ./neo4j-data:/data/
        environment:
            - NEO4J_AUTH=${NEO4J_AUTH}

